import { ModalDialog } from '../shared/ModalDialog';

type Folder = { folderPath: string; name: string; album?: string; trackCount: number };
type Props = { validation: 'idle' | 'checking' | 'valid' | 'invalid'; artistFolders: Folder[] | null; albumFolders: Folder[] | null; artistPath: string; albumPath: string; status: string; onArtistChange: (value: string) => void; onAlbumChange: (value: string) => void; onSave: () => void; onClose: () => void };

export function PersonalAlbumMappingDialog({ validation, artistFolders, albumFolders, artistPath, albumPath, status, onArtistChange, onAlbumChange, onSave, onClose }: Props) {
  return <ModalDialog label="Manual personal album match" onClose={onClose}>
    <div className="artist-summary-dialog-header"><h2>Manual personal album match</h2></div>
    {validation === 'invalid' ? <><p>Cannot make one-to-one track associations for this folder.</p><div className="form-actions"><button type="button" onClick={onClose}>OK</button></div></> : <><p>Select the base artist folder and then the album folder. The app will validate every track before enabling Save.</p><label>Artist folder<select value={artistPath} onChange={(event) => onArtistChange(event.target.value)} disabled={!artistFolders}><option value="">{artistFolders ? 'Choose artist folder' : 'Loading artist folders...'}</option>{artistFolders?.map((folder) => <option key={folder.folderPath} value={folder.folderPath}>{folder.name} ({folder.trackCount} tracks)</option>)}</select></label><label>Album folder<select value={albumPath} onChange={(event) => onAlbumChange(event.target.value)} disabled={!artistPath || !albumFolders || validation === 'checking'}><option value="">{artistPath ? 'Choose album folder' : 'Choose an artist first'}</option>{albumFolders?.map((folder) => <option key={folder.folderPath} value={folder.folderPath}>{folder.album || folder.name} ({folder.trackCount} tracks)</option>)}</select></label>{status ? <p className="hint">{status}</p> : null}<div className="form-actions"><button type="button" disabled={validation !== 'valid'} onClick={onSave}>Save Mapping</button><button type="button" className="secondary-button" onClick={onClose}>Cancel</button></div></>}</ModalDialog>;
}
