export type CdEntry = {
  id: number;
  title: string;
  artist: string;
  year: number | null;
  country: string | null;
  label: string | null;
  format: string | null;
  genre?: string | null;
  style?: string | null;
  estimatedValue: number | null;
  estimatedValueIsManual?: boolean;
  estimatedValueReviewedAt?: string | null;
  notes: string | null;
  discogsId: number | null;
  discogsUri: string | null;
  catalogNumber: string | null;
  barcode: string | null;
  mediaCondition: string | null;
  valueLastCheckedAt: string | null;
  discogsLastSoldAt?: string | null;
  discogsMarketLow?: number | null;
  discogsMarketMedian?: number | null;
  discogsMarketHigh?: number | null;
  discogsMarketCurrency?: string | null;
  discogsMarketStatsCheckedAt?: string | null;
  hasCover?: boolean;
  coverImageUpdatedAt?: string | null;
  artistSummary?: string | null;
  discogsNotes?: string | null;
  discogsNotesSource?: 'release' | 'album' | 'artist' | null;
  discogsContextUpdatedAt?: string | null;
  personalAlbumFolderPath?: string | null;
  personalAlbumFolderMappedAt?: string | null;
};
